# Generated by Django 4.1.7 on 2023-04-15 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Numero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Table', models.CharField(max_length=191)),
                ('Nom', models.CharField(max_length=191)),
                ('Serveur', models.CharField(max_length=191)),
                ('Tel', models.CharField(max_length=191)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_addedunique', models.DateField(auto_now_add=True)),
                ('encourspreparation', models.BooleanField(default=False)),
                ('Servir', models.BooleanField(default=False)),
                ('Total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serveur', models.CharField(max_length=191)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_addedunique', models.DateField(auto_now_add=True)),
                ('Total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=60)),
                ('numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.numero')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('price', models.DecimalField(decimal_places=0, max_digits=7)),
                ('slug', models.SlugField()),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('available', models.BooleanField(blank=True, default=False)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.categories')),
            ],
        ),
        migrations.CreateModel(
            name='LineItemSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=7)),
                ('quantity', models.IntegerField()),
                ('date_addedunique', models.DateField(auto_now_add=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.sale')),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=7)),
                ('quantity', models.IntegerField()),
                ('date_addedunique', models.DateField(auto_now_add=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=0, max_digits=7)),
                ('quantity', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce_app.product')),
            ],
        ),
    ]
